### ISSUE TITLE
How to redirect from http as well as https to new https?

### ISSUE THREAD

**Issue by scheung38** [bendrucker/hapi-require-https#28]
how do redirect http and https to new https thanks

i.e http://www.example.pro/service/api or https://www.example.com/service/api -> https://www.example.pro/service/PX/api, note also need to concat /<PX> which can change for every 
redirect.

**Comment by bendrucker** [comment]
Hi, custom redirection is up to you. This plugin is specifically for redirecting to the same path. You could pick up the request on the https side and send back another redirect to the end URL if you don't mind a second redirect. Otherwise, this library is small enough that you should just copy and modify it for your custom application requirements as allowed by the license.
